### ISSUE TITLE
Alignment tools problem

### ISSUE THREAD

**Issue by reelpilot** [smeighan/xLights#1192]
When selecting two or more effects and utilizing the alignment tools, often times the alignment won't work when the two effects are outside of the viewable screen area. Sometimes it will work, but at least half of the time it doesn't. I've noticed this behavior for years, so it's not a new issue. Below is a link to a short video showing the problem in action. 

[https://youtu.be/3xO9jba1pY8](url)

**Comment by AzGilrock** [comment]
I noticed the issues when working on the 3D Layout.  I had all the problems fixed but we never merged in my code.

**Comment by reelpilot** [comment]
I know Keith did a bug fix of the alignment issue in .23, but I'm still running into the problem on .27 right now. 

[https://youtu.be/Y1oqyJt-PkM](url)

**Comment by AzGilrock** [comment]
I've changed all the code for how alignments work and it won't be long before we transition to the 3D code branch so I don't plan on looking at anything unless it's a problem in the 3D version.

**Comment by reelpilot** [comment]
So the fix that Keith tried will be essentially be replaced by your code with transition to 3D? Are we talking a few weeks or more like a month or two?

**Comment by AzGilrock** [comment]
Yes because when it switches to 3D the same code will align 2D and 3D objects.  It would be pointless for me to guess when things will happen in the future.

**Comment by keithsw1111** [comment]
I dont remember fixing this at all. When Gil said he had a fix in 3D I just left this alone. If i did a fix it was likely something different.

**Comment by reelpilot** [comment]
Apparently I misunderstood you at the expo then. You mentioned a fix coming in v23 so I didn't have to wait until the 3D release. Then when I saw the release notes on v23 fixing an alignment bug, I assumed it was for this problem.

**Comment by AzGilrock** [comment]
Ok forget everything I said.  I think somehow I commented about the wrong issue.  There was a different alignment problem with aligning models on the Layout screen that Keith fixed and I was referring to that.  You are talking about alignment of effects so I haven't touched that but I agree I thought I saw a checkin saying this issue was fixed.

**Comment by keithsw1111** [comment]
The alignment fix in 23 was for models on the layout which is also what Gil fixed in 3d.

No work has been done on the alignment of effects in the sequencer recently.

**Comment by reelpilot** [comment]
Ok, well hopefully this is something that can be added to the list.

**Comment by reelpilot** [comment]
I know it's been a while, but I have recently discovered that this problem impacts more than just alignment of effects. Also impacted is updating the color palette of multiple effects by pressing the update button on the color window and pressing the update button on the effect settings window to update effects. In all instances only effects within the viewable screen are changed and those outside of the viewable screen are not changed.

**Comment by AzGilrock** [comment]
I just looked into this.  The alignment tools for effects appears to work even when an effect is offscreen but yes I did confirm trying to hit Update for color changes was only working for effects on the visible screen.  Probably other bulk edit scenarios that do the same.

**Comment by reelpilot** [comment]
I'm still seeing issues with the alignment not working on non visible effects. Sometimes it works and sometimes it doesn't. I have yet find a repeatable condition as to why it doesn't work other than it doesn't work more often than it does work. I know that's not really any help. Let me know if you would like me to make another demo video and package that sequence over.

**Comment by AzGilrock** [comment]
Need to make a video

**Comment by reelpilot** [comment]
Here's a link to the video showing the alignment issues. I'm also packaging the sequence.

https://youtu.be/MesPKNyyzB8

[Alignment.zip](https://github.com/smeighan/xLights/files/3804676/Alignment.zip)

**Comment by AzGilrock** [comment]
Ok I can try this later with your layout.  I'm not at home but one thing I notice is you are in a custom view.  I'm curious if this is only happening in custom views and not the master view.

**Comment by AzGilrock** [comment]
See this is why we always need more info and the video helps.  When I tested it worked but the failure mechanism is when there are effects that are scrolled offscreen above the visible rows whereas I tested having effects offscreen below the visible rows.

**Comment by AzGilrock** [comment]
I'll fix it but you can make it work as is.  Just select everything and then make sure you scroll to the top and it will work.

**Comment by reelpilot** [comment]
Thanks for looking into this Gil.
