### ISSUE TITLE
Trim sequence output to sequence duration

### ISSUE THREAD

**Issue by AzGilrock** [smeighan/xLights#196]
I don't think we are currently trimming the output we write to file if the user reduces the sequence duration.  I believe I've got the GUI honoring the duration value set in the sequence settings but if the file is saved and played on a display it won't match.

**Comment by LightsOnHudson** [comment]
I just used OSX 4.0.18 and i like the way the time is 'cut off / trimmed'

I just tested it and I changed it from 32.5 (the duration it was when I opened the sequence)

I trimmed / re-entered the duration to be 27 seconds.

I visually saw the duration slide to 27. seconds on the sequencer tab

I pressed play, and it stopped at 27 seconds.
I set it back to 32.5 and pressed play and it played to 32.5 :)

Nice job!

**Comment by stevegiron** [comment]
Hello, I'm helping sort the issues and determine which issues are still valid. 
Is this issue still occuring?

**Comment by LightsOnHudson** [comment]
I believe this can be closed as my note indicates it is working properly now as of 4.0.18

**Comment by stevegiron** [comment]
Thanks!

**Comment by AzGilrock** [comment]
I'm not sure this is fixed.  I opened this because I don't think we are truncating the FSEQ output file based on the sequence duration setting.  I believe we've always used the MP3 length to determine the output file length.  So we need to double check whether the size of the FSEQ actually gets smaller when you reduce the duration in the settings.

**Comment by PhilHilton** [comment]
I think this bit me last night. I had an animation sequence to countdown 10 seconds until the start of the show. I shortened it to 10 seconds from the default animation sequence time (30 seconds? Not sure), but I had apparently already rendered at the longer time... The countdown ran as expected, and then nothing happened for a long time (other than me freaking out) while it (I assume) played the rest of the rendered sequence with no activity in it. I was running in the house when it finished and the rest of the show kicked in. ...So I definitely don't think this is fixed yet.

**Comment by AzGilrock** [comment]
Yeah I know it's not fixed.  I looked into it a couple weeks ago and it wasn't as quick to fix as I thought and I had to get back to working on my own sequences.  This has been talked about in our forum and facebook several times.  The advertised work around is after you change a sequence duration you need to close the sequence, delete the FSEQ file, then reopen and save it again.
