### ISSUE TITLE
3D Rotation Attribute missing on certain props

### ISSUE THREAD

**Issue by Fonzi03** [smeighan/xLights#3413]
Win11 64bit
v2022.16

Adjusting props in 3D, when an axis is moved to a certain position within its range the prop will suddenly flip 180 in its axis. The only exposed rotation attribute on these props is RotateX. If RotateY and RotateZ were exposed we could reset the prop or set it precisely where desired. 

Affected Props:
Arches
Candy Canes
Icicles

**To Reproduce**
Rotate an Axis
Rotate another Axis on the same prop
    prop suddenly rotates 180 at a certain point

**Expected behavior**
Prop would smoothly transition without flipping 180 on its axis

<img width="750" alt="Attributes Available" src="https://user-images.githubusercontent.com/38508905/188770170-f8a37841-a8f9-4db7-948b-5cd7df3426f4.png">
<img width="899" alt="Missing Attributes" src="https://user-images.githubusercontent.com/38508905/188770172-a92fb79f-3cf3-43d3-b590-222a5fa93fdf.png">
<img width="265" alt="Prop Flipped" src="https://user-images.githubusercontent.com/38508905/188770174-405880e9-f971-49d6-9cbd-445c801d4b9b.png">
<img width="227" alt="Right Side Up" src="https://user-images.githubusercontent.com/38508905/188770175-28569dd4-0eff-4245-99bc-56224a0ae8d8.png">
[GhostBusters.zip](https://github.com/smeighan/xLights/files/9502020/GhostBusters.zip)

**Comment by AzGilrock** [comment]
If someone fixes it more power to them.  I remember wasting a ton of hours on this when I first created all the 3D stuff.  Its best to never rotate around the X axis unless its the final rotation.  Once you rotate around X and then start doing the other rotations you can end up with a divide by 0 in the math and causes that flip.  Also if I remember correctly there is a reason I did not expose the Y and Z rotation parameters.  I don't believe they exist.  All because you rotate around the Y axis does not mean I'm storing that as a Y rotation.  All I had to do was recalculate the 2 endpoint positions so as you rotate around Y I just recalculate X, Y, Z positions for the 2 endpoints so there is no Y rotation parameter for us to let you zero out.  If you zero out the X rotation field it should straighten out the model.

**Comment by AzGilrock** [comment]
Also my comment above only applies to the 3 point models Arch, Candy Cane, and Icicles.

**Comment by Fonzi03** [comment]
Zeroing out the x does not correct the issue. I tried that at first. Once a prop is in that state I cannot seem to get it back to a neutral position.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AzGilrock** [comment]
You could always look in the XML file with a text viewer and see if there are Y and Z parameters that are non-zero.  I really thought I had fixed this way back when.  I'd be curious to run some older versions to see if behavior changed anywhere along the way.

**Comment by Fonzi03** [comment]
The XML has the same data that is available in the software. So only the Rotate X parameter is written there as well.

**Comment by AzGilrock** [comment]
That means it doesn’t exist for Y and Z

**Comment by Fonzi03** [comment]
Being that it exists on other props is there any way to treat these the same so they can have it as well? With varying terrain elevations almost all of my props require multiple axis adjustments to line up properly.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AzGilrock** [comment]
Do you know how to Package a sequence.   The file you attached does not have your layout it just has a sequence file.  The xlights_rgbeffects.xml file is where I'd see the issue.

**Comment by dkulp** [comment]
The various props that don't have it is because it does not make sense for those props.   In fact, the RotateX is actually not a rotate X either.   Those props have a starting point, and ending point, and the rotation is actually a rotation around the line created from those two points.

**Comment by AzGilrock** [comment]
Actually I don't need a layout I see exactly how to create it.  There is code in the ThreePointLocation model that was supposed to correct this.  Need to see why its not working now.  This happens when the green square is on the right side of the blue square if the points have been moved so they aren't on the same plane.  I see where I created a RotateX1 matrix to do a 180 flip around X to correct it when detected but some other code change might have made it so this code needed to be different.

**Comment by AzGilrock** [comment]
@dkulp It appears that code I had to detect when to flip isn't needed anymore.  If I comment out line 252 of ThreePointModelLocation the issue goes away.  So apparently something fixed the need to do that correction.

**Comment by AzGilrock** [comment]
Seems like it was working that way when 3D first released so I'm wondering if there is some other scenario that can cause a flip that the code was fixing but its definitely breaking it for the steps I'm doing now.

**Comment by merryoncherry** [comment]
I have some icicles that flip when I "rotate them" (move the ends) certain ways, if you need a layout file.  Seems like you don't though.  I had forgotten about this because I stopped doing that rotation; they now remain on a horizontal plane instead of having one end higher than the other.

**Comment by AzGilrock** [comment]
If you never make the Green square positioned to the right of the Blue square you will never see a problem.

**Comment by AzGilrock** [comment]
Its caused so many issues over the years I've felt like making the square swap whenever someone tries to do that.

**Comment by Fonzi03** [comment]
I can try that and then for certain props choose blue square as the start instead of green. For consistency I usually set/ rotate everything so the green square is the start though.

Also as far as green square to the right of blue square that's all relative in 3d, so is that based off the default position?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AzGilrock** [comment]
@dkulp Here's a layout with 2 arches.  That was the issue I was trying to fix with the RotateX1 flip I'm doing at line 252 of the ThreePointScreenLocation.  If you comment out that line then both these arches flip and the other one ends upside down.  I think my thought was the arch should never look upside down.  If you move the green square of each arch with the red handle to move it back and forth across the blue square you can see one will flip but the other doesn't.  Comment out that line and the behavior swaps to the other arch.

[xlights_rgbeffects.xml.zip](https://github.com/smeighan/xLights/files/9540972/xlights_rgbeffects.xml.zip)

**Comment by AzGilrock** [comment]
I have an update to improve this but I think I messed up using Git on the Mac.  I did a commit and then couldn't push because I wasn't on a branch and then when checking out master it appeared to delete my work.  Mainly just explaining why I have a push to the readme with no code....will fix it shortly.

**Comment by computergeek1507** [comment]
look if the code got stashed

**Comment by AzGilrock** [comment]
Its weird cause I did a "git commit" command and I don't see the commit when I do a "git log".  It's like it did a reset hard by default.  Anyways it wasn't much code so I can write it in 5 minutes.  I think my mistake was doing a "git checkout origin/master" which creates a detached head instead of "git checkout master"

**Comment by AzGilrock** [comment]
Ok I checked in an improvement.  This video shows the issue.  Watch what happens halfway through when I start moving the green handle back and forth.  The arch tilts when it shouldn't.  With this update it won't do that anymore.  The only thing I see is if you rotate around the Z axis with the blue rotate handle the arch will flip upright when the green handle gets on the right side of the blue handle.  If you really need it upside down then add X rotation with the red handle.
https://youtu.be/6BQtB-eWhEQ

**Comment by Fonzi03** [comment]
So just to clarify whenever I was making an adjustment it was not with the resizing arrows it was with the movement/rotation arrows.

If they behave similarly then at least you are able to get it back to a normal state whereas with the version I have once your out of whack there's no way to bring it back to normal (technically there is the it would be very hard to line it up perfectly).

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AzGilrock** [comment]
Yeah I know what you were doing but it doesn’t make a difference because of the way we draw it.  It’s easier to demonstrate the issue moving the endpoint.  The rotations you were doing just end up causing a recalc of the endpoints and add x rotation so it’s like doing 3 separate moves at once.  Also realize if you were causing the green square to be past the blue square in X then some of you’re effects will draw backwards.  Like a single strand or morph that is meant to go left to right will always go green square to blue square.

**Comment by AzGilrock** [comment]
Should be fixed in latest release

**Comment by Fonzi03** [comment]
Got it, thank you. I am always organizing props in a way in which the green square is the start. I also setup my viewpoints from angles which allow the effect to display properly. IE 45 degree angle for arches which round a corner and straight shot for matrix meshes.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AzGilrock** [comment]
So did the changes work out better?

**Comment by Fonzi03** [comment]
Sorry I've been crazy busy with work and barely able to spend any time messing with it. My first attempt it still flipped around and although the behavior seemed different I could still get it to flip when it didn't seem like it should. Although, that particular one was already out of whack from the previous version so I deleted it and have not tried to reinsert it as a new prop to confirm. I will try to jump in this weekend and check.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
