### ISSUE TITLE
Fire effect drops off on right side of effect

### ISSUE THREAD

**Issue by Darzoom** [smeighan/xLights#3867]
**Describe the bug**
When adding Fire effect to any model, the right side is cut off.  It is especially prominent on a matrix or window. 
**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Add Fire effect to Matrix or window
2. See results

**Expected behavior**
Fire across model evenly

I changed to oversized buffer and it would fill the right side but colors were impacted.  

**Versions (please complete the following information):**
 - OS: Monterey 16.6.7
 - xLights version 2023.10

[fire effect.zip](https://github.com/smeighan/xLights/files/11948851/fire.effect.zip)

**Comment by Darzoom** [comment]
Seems to have been impacted with the changes from 2022.17 and 2022.18.

**Comment by merryoncherry** [comment]
Would like one of the devs to evaluate this.  I think the use of maxWi vs maxMWi is not consistent, but also I wonder why maxMWi is set differently when the fire is from the side positions.

Possible patch that worked for me:

```
diff --git a/xLights/effects/FireEffect.cpp b/xLights/effects/FireEffect.cpp
index 68934c10e..155f21c2b 100644
--- a/xLights/effects/FireEffect.cpp
+++ b/xLights/effects/FireEffect.cpp
@@ -222,15 +222,13 @@ void FireEffect::Render(Effect* effect, const SettingsMap& SettingsMap, RenderBu
     int maxMWi = maxBuffer.x == -1 ? buffer.BufferWi : maxBuffer.x;
     int maxMHt = maxBuffer.y == -1 ? buffer.BufferHt : maxBuffer.y;
     if (loc == 2 || loc == 3) {
-        maxMHt = buffer.BufferWi;
-        maxMWi = buffer.BufferHt;
+        std::swap(maxMHt, maxMWi);
     }

     int maxWi = buffer.BufferWi;
     int maxHt = buffer.BufferHt;
     if (loc == 2 || loc == 3) {
-        maxHt = buffer.BufferWi;
-        maxWi = buffer.BufferHt;
+        std::swap(maxHt, maxWi);
     }

     if (maxMHt < 1)
@@ -257,7 +255,7 @@ void FireEffect::Render(Effect* effect, const SettingsMap& SettingsMap, RenderBu
     }
     int step = 255 * 100 / maxHt / HeightPct;
     for (int y = 1; y < maxHt; ++y) {
-        for (int x = 0; x < maxWi; ++x) {
+        for (int x = 0; x < maxMWi; ++x) {
             int v1 = GetFireBuffer(x - 1, y - 1, cache->FireBuffer, maxMWi, maxMHt);
             int v2 = GetFireBuffer(x + 1, y - 1, cache->FireBuffer, maxMWi, maxMHt);
             int v3 = GetFireBuffer(x, y - 1, cache->FireBuffer, maxMWi, maxMHt);
```

**Comment by keithsw1111** [comment]
I downloaded the sample show folder and not seeing the issue so I am assuming this has been fixed at some point.

**Comment by merryoncherry** [comment]
@keithsw1111 There's an open PR, I think it happens without the PR.

**Comment by keithsw1111** [comment]
I am not using the PR

**Comment by merryoncherry** [comment]
This is still happening for me on master.
Just drop a default fire effect on any matrix and you will see that the right side doesn't fill in properly.
Also, on inspection, the code is very inconsistent about what it is doing... that's what the PR fixes and then the effect looks the same on both sides.
![image](https://github.com/smeighan/xLights/assets/102841136/d255a4df-8450-463b-9b98-cb9e44f43bcd)
