### ISSUE TITLE
LOR to Xlights import (.SUP) issues V2016_38

### ISSUE THREAD

**Issue by bluzervic** [smeighan/xLights#609]
(.SUP) file import for a horizontal matrix is not working.
Matrix is 12 strings x 50 nodes bottom left is 1st node
see included files - importing into pixel-cane partyhouse
Included 2 (.sup files)

[partyhouse.zip](https://github.com/smeighan/xLights/files/342472/partyhouse.zip)

How it should look:
https://www.youtube.com/watch?v=bJBTDBYgUFo

**Comment by stevegiron** [comment]
This was fixed in V39 which was just released today.

**Comment by AzGilrock** [comment]
Actually there were additional problems I didn't notice till I saw his files.  I think I've got it fixed with a checkin I just did 10 minutes ago.  It's so frustrating because most of this mess is because Brian kept all the coordinates as if everything was vertical instead of horizontal so I have all this special code to swap the x and y coordinates and sometimes the Y values need to be flipped.  I'm sure there may be a couple cases I may have missed.

For this sequence I notice the Text comes out a little off.  That will need to be fixed manually for now unless one of us can figure out a better conversion.  Matching the fonts isn't perfect.

**Comment by stevegiron** [comment]
I sent you another sequence Gil that works much better with v39. It just has a small section that needs fine tuning on the conversion.

**Comment by bluzervic** [comment]
yea LOR does have some font types Xlights does not have....I have been able to adjust to this in the past. Once the release is ready to test I will give it a go.... Thanks guys, you all rock

**Comment by AzGilrock** [comment]
I just got another file from someone showing it's still not right.  Man I've wasted like 6 hours trying to fix this SuperStar stuff.

**Comment by bluzervic** [comment]
I tested version (.39) and still no go.
Could there be an option to import a vertical matrix verses a horizontal matrix as changing values in X and Y probably does nothing to the import.

**Comment by bluzervic** [comment]
By the way... the image shows up as a vertical matrix, upside down.

**Comment by AzGilrock** [comment]
Well it looked pretty good to me.  I'm importing the file named "WOWC-PartyRockAnthem-Screen-left.sup" onto the model name "Matrix" that is over the garage.  Everything looks good except some text effects will need you to adjust them.  There's not a perfect import for text.

**Comment by bluzervic** [comment]
it actually imports upside down but is horizontal. What settings did you use. Maybe I am not importing correctly. Text is not an issue that is easily fixed

**Comment by AzGilrock** [comment]
Here's what it looks like when I import using Default settings:
https://youtu.be/YtItaHh39Co

**Comment by AzGilrock** [comment]
Ok you're right its still broke in v39.  I'm running the code about to go into v40 and there are at least 3 or 4 checkins that fixed SuperStar import stuff.  At least you can see a snippet of what it will look like.

**Comment by AzGilrock** [comment]
I think this got fixed.  If so you can hit close.
