### ISSUE TITLE
Effect panel missing scrollbars

### ISSUE THREAD

**Issue by AzGilrock** [smeighan/xLights#612]
If you open xLights and then open a sequence and click on an effect that should have scrollbars they are missing in the effect window.  Then dragging new effects down doesn't fix the problem it seems the only fix is to tear away the panel and re-dock it.  Now if you're first action for that effect type is to drag and drop it then everything is fine.  So the layout action executes only if you drag and drop the effect first or tear away the panel forcing a resize action.

![missingscrollbar](https://cloud.githubusercontent.com/assets/2024669/16524205/0f0e17a2-3f5c-11e6-9231-bb0544a60696.jpg)

**Comment by keithsw1111** [comment]
I checked every effect and they all look ok now. I am going to assume this got fixed at some point. Either that or it is an intermittent problem ... and i hit it on a good day.

**Comment by dkulp** [comment]
Just a note:  I see this a lot on the Mac, but it's only a startup issue.   Once I resize the window at all, it appears and is fine.

**Comment by AzGilrock** [comment]
Sorry Keith this problem has never been fixed.  I just confirmed it.  It has to be exactly like I stated to see it.  The pain is that you have to resize the panel for every different effect type.  Just fixing it for say the Text effect doesn't fix it for the Morph effect.  I made a video tos how the issue:
https://youtu.be/YLVJaRtZmgo
